# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
NEG_PREFIX: neg_
LABEL_FIELD: label
load_col:
    inter: [user_id, item_id, rating]
val_interval:
    rating: "[3,inf)"
unused_col:
    inter: [rating]

# training and evaluation
epochs: 500
train_batch_size: 4096
valid_metric: MRR@10
eval_batch_size: 4096000

embedding_size: 64
n_layers: 3
reg_weight: 1e-4

ssl_temp: 0.1
ssl_reg: 1e-6
hyper_layers: 1

alpha: 1.5

proto_reg: 8e-8
num_clusters: 10

m_step: 1
warm_up_step: 20

learning_rate: 0.002

